project:
  type: website

website:
  title: "VirusBank"
  site-url: https://phylotree.data-intuitive.app
  repo-url: https://github.com/data-intuitive/VirusBank
  page-footer: "Copyright 2023, Data Intuitive"
  sidebar:
    contents:
      - index.qmd
format:
  html:
    title-block-banner: virus.jpg
    anchor-sections: true
    smooth-scroll: true
    fontcolor: "rgb(35, 70, 106)"
    sidebar: false
    page-layout: full
    theme: pulse # sandstone # yeti # spacelab
    mainfont: "Mukta"
    font-size: 16em
    css: styles.css
    toc: false
    resources: 
      - virus.png
      - tree.newick
      - annotations.json
      - toolbox/toolbox.json
      - toolbox/img/tb_target-based-assays.png
      - toolbox/img/tb_animal-infection-models-2.png
      - toolbox/img/tb_animal-infection-models.png
      - toolbox/img/tb_cell-based-assays.png
      - toolbox/img/tb_ex-vivo-models.png
      - toolbox/img/tb_ex-vivo-models2.png
      - toolbox/img/tb_recombinant-viruses.png
      - toolbox/img/tb_high-throughput-screening.png
      - toolbox/img/tb_target-based-assays.png
