project:
  type: website

website:
  title: "VirusBank"
  repo-url: https://github.com/data-intuitive/VirusBank
format:
  html:
    title-block-banner: virus.jpg
    anchor-sections: true
    smooth-scroll: true
    fontcolor: "rgb(35, 70, 106)"
    sidebar: false
    page-layout: full
    theme: pulse # sandstone # yeti # spacelab
    mainfont: "Mukta"
    font-size: 16em
    css: styles.css
    toc: false
    resources: 
      - tree.newick
      - family.xlsx
      - toolbox/toolbox.json
      - toolbox/img/tb_target-based-assays.png
      - toolbox/img/tb_animal-infection-models-2.png
      - toolbox/img/tb_animal-infection-models.png
      - toolbox/img/tb_cell-based-assays.png
      - toolbox/img/tb_ex-vivo-models.png
      - toolbox/img/tb_ex-vivo-models2.png
      - toolbox/img/tb_recombinant-viruses.png
      - toolbox/img/tb_high-throughput-screening.png
      - toolbox/img/tb_target-based-assays.png
      - img/placeholder.jpg
      - _js/funtions.js
      - _js/family.qmd
      - _js/virus-breadcrumb.qmd
